name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello, world!"
```[_{{{CITATION{{{_1{Quickstart for GitHub Actions](https://docs.github.com/en/actions/writing-workflows/quickstart)

