name: Discussion Comment

on:
  discussion:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Add comment
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }}/comments \
          -d '{"body":"Thanks for starting a discussion! Please check out [this link](https://example.com) for more information."}'
