name: Discussion Comment

on:
  discussion:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Add comment
        run: |
          curl -v -X POST -H "Authorization: token ${{ secrets.CMM }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/discussions/${{ github.event.discussion.number }}/comments \
          -d '{"body":"Thanks for starting a discussion! Please check out [this link](https://example.com) for more information."}'
